### ISSUE TITLE
Root location

### ISSUE THREAD

**Issue by olivierberthomme** [OBone-git/Cozytouch-domoticz#2]
Certains équipements (Chauffe eau thermoynamique Thermor) pourraient être liés à la _rootPlace_ et non pas une _subPlaces_
Vu pour la classe **io:AtlanticDomesticHotWaterProductionIOComponent** et **io:DHWCumulatedElectricalEnergyConsumptionIOSystemDeviceSensor**

Sous ensemble du JSON pour analyse/test:
[Thermo-dyn.json.txt](https://github.com/OBone-git/Cozytouch-domoticz/files/3866002/Thermo-dyn.json.txt)

**Comment by OBone-git** [comment]
#5

**Comment by olivierberthomme** [comment]
Fonctionne en partie : mon chauffe eau est un "Thermor AéroMax 4" fonctionnant sur le principe de pompe à chaleur Air/Eau.

Il est créé dans Cozytouch avec la classe "io:AtlanticDomesticHotWaterProductionIOComponent" mais j'ai vu que le script le détecte beaucoup mieux s'il cette classe matche sur "chauffe eau thermodynamique V3" au lieu de "chauffe eau". Je retrouve toutes les fonctions de Cozytouch dans Domoticz (modes Auto/ManuelEco/Manuel) et les durée de Boost et d'absence.

Je pense qu'il faut plutôt arriver à re-classifier mon équipement. Sur l'issue, il y a le JSON concernant mon chauffe eau. Reste à trouver un JSON d'un chauffe eau (standard) pour trouver à différencier les 2 équipements...

Par contre, même classifié en thermodyV3, il ne prend pas la bonne location (il est parti sur ma 1ère salle).

**Comment by OBone-git** [comment]
OK je n'avais pas fait attention à cela.
Le "io:AtlanticDomesticHotWaterProductionIOComponent" était le premier composant que j'ai intégré au script et était un ballon d'eau chaude sans PAC. 
Je n'ai plus de retour de qui que ce soit sur ce genre d'équipement donc je fusionne les classes "io:AtlanticDomesticHotWaterProductionIOComponent" et "io:AtlanticDomesticHotWaterProductionV3IOComponent".
La classe d'un ballon standard a peut être évoluer.

Pour le label, c'est corrigé.

Correction (à tester) #7
