### ISSUE TITLE
Intégration Atlantic Agilia (États lus mais non modifiés...)

### ISSUE THREAD

**Issue by benjdev** [OBone-git/Cozytouch-domoticz#21]
Bonjour,
Tout d'abord un immense merci pour ce script au top, sacré boulot...
J'ai récupéré un lot de Atlantic agilia avec le bridge et je souhaite les associer à mon Domoticz.
J'ai donc trouvé ton script, idéal pour moi.
J'installe tout ça en suivant le readme ainsi que le fil de discussion du forum et tout fonctionne au niveau de la création des devices, et les températures remontent bien ainsi que l'état des radiateurs par contre pas de modification lorsque je modifie l'état à partir de Domoticz... 🤔
Je ne maîtrise pas trop le fonctionnement du script donc je ne vois pas trop vers où fouiller pour tenter de résoudre ce souci...
D'avance merci de vos réponses, ou pistes à creuser !
Benjamin

**Comment by OBone-git** [comment]
Hello, merci, il faut que je regarde tes données JSON (avec un dump debug=2) pour analyser cela, réponse par mail ou via MP sur https://easydomoticz.com/forum/viewtopic.php?f=17&t=4671

**Comment by benjdev** [comment]
Yep ! merci de ton retour rapide surtout...
J'ai fait et je vais essayer de décortiquer.
Je pose ici et j'irais mettre sur easydomoticz rapidement :
`¤¤¤¤ Demarrage script cozytouch <=> domoticz version 4 (debug :2)
Version python : 2.7.9
**** Test existence / creation configuration cozytouch (hardware domoticz + fichier de sauvegarde) ****
Fichier de sauvegarde de la configuration : /home/pi/domoticz/scripts/python/cozytouch_save
Fichier de sauvegarde de la configuration inexistant, creation hardware cozytouch dans domoticz et nouveau fichier de sauvegarde
Traceback (most recent call last):
  File "cozytouch.py", line 1554, in <module>
    if test_exist_cozytouch_domoticz_hw_and_backup_store():
  File "cozytouch.py", line 448, in test_exist_cozytouch_domoticz_hw_and_backup_store
    d=shelve.open(cozytouch_save,'c')
  File "/usr/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python2.7/shelve.py", line 223, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "/usr/lib/python2.7/dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBAccessError: (13, 'Permission denied')`
La dernière ligne me pose question... je cherche de mon côté et mettrais aussi si j'avance ;)
Bonne journée à toi !

**Comment by benjdev** [comment]
Problème résolu par une ré-installation complète de Domoticz : mon install était ancienne et beaucoup de choses ayant changé dans la maison c'était nécessaire...
Il semble qu'il s'agisse d'un bug connu de Python 2.7, résolu mais visiblement mes MÀJ ne suffisaient pas.

Donc ça fonctionne plutôt pas mal donc encore un immense merci.
Je vais essayer de fouiller pour voir si je pourrais ajouter un sélecteur qui règle directement la température de consigne, comme sur l'appli Cozytouch... (je reviens si j'ai du neuf !)
