### ISSUE TITLE
MAJ données

### ISSUE THREAD

**Issue by OBone-git** [OBone-git/Cozytouch-domoticz#4]
Pourrais-tu changer le comportement des mises à jour dans Domoticz pour n'envoyer les valeurs que si elles sont différents de celles actuels (pour éviter mises à jour continues des températures de consigne par exemple) ?

**Comment by OBone-git** [comment]
Peux tu me faire un retour de ton coté  afin que je ferme l'issue ?

**Comment by olivierberthomme** [comment]
Dernier pull request je pense. J'ai mis ce code sur mon installation.

**Comment by OBone-git** [comment]
Ok merci 😊
