### ISSUE TITLE
New hardware for new version

### ISSUE THREAD

**Issue by olivierberthomme** [OBone-git/Cozytouch-domoticz#52]
This check is annoying for me and cannot understand the value.
Why every time we upgrade the script, the script creates a new hardware and its devices?

https://github.com/OBone-git/Cozytouch-domoticz/blob/fb75a0b2eed48def20edfe1a62e277151d1f5e44/cozytouch.py#LL527C92-L527C92

In Domocicz, I configured all my devices on v4. Some have schedules, others have DZ scripts. Every time I upgrade, I need to review all this stuff.
What do you think of removing the re-creation on new version?

**Comment by olivierberthomme** [comment]
Found a basic workaround: rename the domoticz hardware before 1st execution of the new version.
Anyway, removing this version in the hardware name could be an improvement IMHO.

**Comment by olivierberthomme** [comment]
No feedback ; workaround provided

**Comment by Tatroxitum** [comment]
I agree, implemented in pull request https://github.com/OBone-git/Cozytouch-domoticz/pull/54#issue-1775547343
